sudo: false
dist: trusty
language: generic

addons:
  apt:
    packages:
      - libpango1.0-dev
      - libcairo2-dev
      - libgtk2.0-dev

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.local/bin
  - $HOME/.stack
  - .stack-work

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - if [[ ! -x ~/.local/bin/stack ]]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
  - stack --version

  # GHC
  - stack setup
  - stack exec -- ghc --version

install:
  - travis_wait stack --no-terminal install halma --only-dependencies
  - travis_wait stack --no-terminal install --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps