flags: {}
nix:
  enable: true
  packages:
  - cairo
  - glib
  - gtk2
  - pango
  - pkgconfig
  - zlib
packages:
- halma
- halma-gui
- halma-telegram-bot
extra-deps:
- amazonka-1.6.0
- amazonka-core-1.6.0
- amazonka-s3-1.6.0
- dual-tree-0.2.2
- diagrams-cairo-1.4.1
- diagrams-core-1.4.1
- diagrams-gtk-1.4
- diagrams-lib-1.4.2.2
- diagrams-rasterific-1.4.1
- diagrams-solve-0.1.1
- gio-0.13.5.0
- grid-7.8.9
- gtk-0.14.10
- http-types-0.10
- mmorph-1.0.9
- mvc-1.1.6
- telegram-api-0.7.2.0
- servant-0.12.1
- servant-client-0.12.0.1
- servant-client-core-0.12
resolver: lts-11.11
