flags: {}
packages:
- halma
- halma-gui
- halma-telegram-bot
extra-deps:
- diagrams-gtk-1.4
- diagrams-rasterific-1.4
- grid-7.8.9
- mvc-1.1.6
- telegram-api-0.7.2.0
- servant-0.12.1
- servant-client-0.12.0.1
- servant-client-core-0.12
- gtk-0.14.7
- mmorph-1.0.9
- gio-0.13.4.1
- timeit-2.0
resolver: lts-10.7
