flags: {}
nix:
  enable: true
  packages:
  - cairo
  - glib
  - gtk2
  - pango
  - pkgconfig
  - zlib
packages:
- halma
- halma-gui
- halma-telegram-bot
extra-deps:
- grid-7.8.12
- mvc-1.1.7
- git: https://github.com/Znack/haskell-telegram-api.git
  commit: 7020377c5285c4f5818cdeff5972c0c738dad20a
resolver: lts-12.26
